version: '3'

services:
  # Express App
  app:
    container_name: express-app
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://admin:password@db:5432/webhook-db

  # PostgresSQL Database
  db:
    container_name: postgres-db
    image: postgres:16.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: webhook-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
